[project]
name = "qass-tools-networking"
version = "3.8"
authors = [
  {name="Oliver Kowollik", email="okowollik@qass.net" },
  {name="Sammy Joe Lüling", email="slueling@qass.net" }
]
description = "Networking package for qass_tools"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [                   
    "numpy>=1.19.5",
    "packaging"
]

[project.optional-dependencies]
# development dependency groups
developers = [
    "pytest",
    "sphinx",
    "sphinx_toolbox",
    "sphinx_design",
    "sphinx-rtd-theme"
]

[project.urls]
Homepage = "https://qass.github.io/"

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
