[metadata]
name = qass_tools_networking
version = 2.0.1
author = Oliver Kowollik
author_email = okowollik@qass.net
description = Networking package to communicate with the Analyzer4D
long_description = file: README.md
long_description_content_type = text/markdown
url = https://git.qass.net/developers/qass_tools/qass_tools_networking
project_urls =
    Bug Tracker = https://git.qass.net/developers/qass_tools/qass_tools_networking/-/issues
classifiers =
    Programming Language :: Python :: 3
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find_namespace:
python_requires = >=3.6
install_requires = 
    numpy >=1.19.5
    retry

[options.packages.find]
where = src
